FAULTS
-- Name  I1  I2  J1  J2  K1  K2  Face ( I/J/K )
'CRACK'     1   1     9   9     1   9     'Y'       / 
'CRACK'     2   2     9   9     1   9     'Y'       / 
'CRACK'     3   3     9   9     1   9     'Y'       / 
'CRACK'     4   4     9   9     1   9     'Y'       / 
'CRACK'     5   5     9   9     1   9     'Y'       / 
'CRACK'     6   6     9   9     1   9     'X'       / 
'CRACK'     6   6     9   9     1   9     'Y'       / 
'CRACK'     7   7     8   8     1   9     'Y'       / 
'CRACK'     8   8     8   8     1   9     'X'       / 
'CRACK'     8   8     8   8     1   9     'Y'       / 
'CRACK'     9   9     7   7     1   9     'Y'       / 
'CRACK'     10   10     7   7     1   9     'Y'       / 
'CRACK'     11   11     7   7     1   9     'Y'       / 
'CRACK'     12   12     7   7     1   9     'X'       / 
'CRACK'     12   12     7   7     1   9     'Y'       / 
'CRACK'     13   13     6   6     1   9     'Y'       / 
'CRACK'     14   14     6   6     1   9     'Y'       / 
'CRACK'     15   15     6   6     1   9     'Y'       / 
'CRACK'     16   16     6   6     1   9     'Y'       / 
'CRACK'     17   17     6   6     1   9     'Y'       / 
'CRACK'     18   18     6   6     1   9     'Y'       / 
'CRACK'     19   19     6   6     1   9     'Y'       / 
'CRACK'     20   20     6   6     1   9     'Y'       / 
/

MULTFLT
    'CRACK' 0.0 /
/